spring.application.name=InvestApp

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:${DB_PORT:3307}/${MYSQL_DATABASE:investapp}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USER:finance_user}
spring.datasource.password=${MYSQL_PASSWORD:finance123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:sua-chave-secreta-super-segura-minimo-64-caracteres-para-hs512-algorithm-test}
app.jwt.expiration=${JWT_EXPIRATION:3600000}